routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('frontpage.layout.home');
});*/

Route::get('/', 'FrontEnd\HomeController@index');
Route::get('/artikel/detail/{idPertanyaan}/{kategori}/{linkSeo}', 'FrontEnd\HomeController@artikel');
Route::get('/artikel/kategori/{idKategori}/{kategori}', 'FrontEnd\HomeController@kategori');
Route::get('/galeri', 'FrontEnd\HomeController@galeri');
Route::post('/komentar', 'FrontEnd\HomeController@store');


Route::get('/reset', function () {
    return view('auth.passwords.email');
});

Route::get('/recover', function () {
    return view('auth.passwords.reset');
});






Route::get('/content', function () {
    return view('frontpage.layout.content');
});


// auth route 
Route::get('/login', 'AuthController@login')->name('login');
Route::post('/postlogin', 'AuthController@postlogin');
Route::get('/logout', 'AuthController@logout');
Route::post('/signup', 'AuthController@signup');

// catatan route yg masuk admin panel dimasukkan kedalam route group ini!!
Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin', 'AdminController@index')->name('HOME');
});


Route::resource('/admin/artikel', 'ArtikelController');
Route::resource('/admin/kategori', 'kategoriController');
Route::resource('/admin/komentarArtikel', 'komentarArtikelController');
Route::resource('/admin/foto', 'fotoController');
Route::resource('/admin/iklan', 'iklanController');
Route::resource('/admin/user', 'userController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/adminpage/layout/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="/" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="/data-tables" class="nav-link">Data-Tables</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">

    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-user-cog"></i>
      </a>
      <div class="dropdown-menu dropdown-menu dropdown-menu-right">
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> Profile

        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> Setting

        </a>
        <div class="dropdown-divider"></div>
        <a href="/logout" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> Logout

        </a>

    </li>
  </ul>
</nav>

resources/views/adminpage/layout/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="../../index3.html" class="brand-link">
    <img src="{{asset('adminpage_asset/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Tugas Akhir</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{asset('adminpage_asset/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{auth()->user()->name}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

        <li class="nav-item">
          <a href="{{route('artikel.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Artikel
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('kategori.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Kategori
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('komentarArtikel.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Komentar Artikel
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('foto.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Galeri Foto
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('iklan.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Iklan
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('user.index')}}" class="nav-link">
            <i class="nav-icon fas fa-info-circle"></i>
            <p>
              Manajemen User/Penulis/Admin
            </p>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>