routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('frontpage.layout.home');
});*/

Route::get('/', 'FrontEnd\HomeController@index');
Route::get('/artikel/detail/{idPertanyaan}/{kategori}/{linkSeo}', 'FrontEnd\HomeController@artikel');
Route::get('/artikel/kategori/{idKategori}/{kategori}', 'FrontEnd\HomeController@kategori');
Route::get('/galeri', 'FrontEnd\HomeController@galeri');
Route::post('/komentar', 'FrontEnd\HomeController@store');


Route::get('/reset', function () {
    return view('auth.passwords.email');
});

Route::get('/recover', function () {
    return view('auth.passwords.reset');
});






Route::get('/content', function () {
    return view('frontpage.layout.content');
});


// auth route 
Route::get('/login', 'AuthController@login')->name('login');
Route::post('/postlogin', 'AuthController@postlogin');
Route::get('/logout', 'AuthController@logout');
Route::post('/signup', 'AuthController@signup');

// catatan route yg masuk admin panel dimasukkan kedalam route group ini!!
Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin', 'AdminController@index')->name('HOME');
});


Route::resource('/admin/artikel', 'ArtikelController');
Route::resource('/admin/kategori', 'kategoriController');
Route::resource('/admin/komentarArtikel', 'komentarArtikelController');
Route::resource('/admin/foto', 'fotoController');
Route::resource('/admin/iklan', 'iklanController');
Route::resource('/admin/user', 'userController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\str;
use Illuminate\Support\faceades\Storage;
USE DB;
USE Auth;
use App\artikelModel;
use App\kategoriModel;
use App\tag;

class ArtikelController extends Controller
{
    public function index (){
        $query = artikelModel::all();
        return view ('adminModul.artikel.index',compact('query'));
    }

public function create (){
        $query = kategoriModel::all();
        return view ('adminModul.artikel.create',compact('query'));
    }
public function store (Request $request){
        $request->validate([
            'judul' => 'required|unique:artikel',
            'isi' => 'required',
            'gambar'         =>  'image|max:2048',
        ]);

        $tags_arr = explode(',', $request["tags"]);

        $tag_ids =[];
        foreach($tags_arr as $tag_name){
                $tag = Tag::where ("tag_name", $tag_name)->first();
                if ($tag){
                    $tag_ids[] = $tag->id;
                }else{
                    $new_tag = Tag::create(["tag_name" =>$tag_name]);
                    $tag_ids[] = $new_tag->id;
                }
                
        } 
               //modelling Assignment         
           $gbrUpload = request()->file('gambar');
           $gbrName = time().'.'. $gbrUpload->getClientOriginalExtension();
           $gbrPath = public_path('/gambar_artikel/');
           $gbrUpload->move($gbrPath, $gbrName);
            $query = artikelModel::create([
                'judul' => $request->judul,
                'isi' => $request->isi,
                'status' => $request->status,
                'link_seo' => Str::slug ($request->judul),
                'gambar' => $gbrName,
                'id_kategori' => $request->kategori,
                'id_user' => Auth:: id()
            ]);
            $query->tags()->sync($tag_ids);
            $user = Auth::user();
            $user->artikel()->save($query);
        return redirect ('admin/artikel')->with('berhasil','Berhasil diSimpan!');
    }
    public function edit($idArtikel){
        //query builder
       // $query = DB ::table('pertanyaan')->where('id',$idPertanyaan)->first();
       // orm 
       $queryKategori = kategoriModel::all();
       $query = artikelModel :: find($idArtikel);
        //dd($query);
        return view ('adminModul.artikel.edit',compact('query','queryKategori'));
    }
    
    public function update($idArtikel, Request $request ){
      if($request->file('gambar') == "")
        {
           $query = artikelModel :: where('id',$idArtikel)->update([
               "judul" => $request["judul"],
               "isi" => $request["isi"],
               'status' => $request->status,
               'id_kategori' => $request->kategori,
                'link_seo' => Str::slug ($request->judul)
                ]);
           }
           else {
            $data = \App\artikelModel::findOrFail($idArtikel);
            unlink('gambar_artikel/'.$data->gambar);
            $gbrUpload = request()->file('gambar');
            $gbrName = time().'.'. $gbrUpload->getClientOriginalExtension();
            $gbrPath = public_path('/gambar_artikel/');
            $gbrUpload->move($gbrPath, $gbrName);
            $query = artikelModel :: where('id',$idArtikel)->update([
                "judul" => $request["judul"],
                "isi" => $request["isi"],
                'status' => $request->status,
                 'link_seo' => Str::slug ($request->judul),
                 'id_kategori' => $request->kategori,
                 'gambar' => $gbrName
                 ]);
           }
           
              
           //dd($query);
           return redirect ('/admin/artikel')->with('berhasil','Berhasil diUpdate!');
       }
       public function destroy($idArtikel){
        
        //orm
        $data = \App\artikelModel::findOrFail($idArtikel);
        unlink('gambar_artikel/'.$data->gambar);
        ArtikelModel::destroy($idArtikel);    
        return redirect ('/admin/artikel')->with('berhasil','Berhasil diHapus!');

}

      
    }

resources/views/adminModul/artikel/create.blade.php
@extends('adminpage.master')
@push('textEditor-tinyMCE')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Data Artikel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Artikel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
    <div class="col-md-12">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Artikel</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('artikel.store')}} " method="post" enctype="multipart/form-data">
              @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Judul</label>
                    <input class="form-control" name="judul" value="{{old('judul','')}}">
                  </div>
                  @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
                  <div class="form-group">
                  <label>Isi</label>
                  <textarea class="form-control my-editor" name="isi">{!! old('isi','') !!}

                  </textarea>
                      </div>
                      @error('isi')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
                  
                <div class="form-group">
                        <label for="exampleFormControlFile1">Tambah gambar</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1" name="gambar">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">status Publikasi</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="status">
                    <option value="YA">YA</option>
                    <option value="TIDAK">TIDAK</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="kategori">
                    @foreach($query as $key => $query )
                    <option value="{{$query -> id}}">{{$query -> nama_kategori}}</option>
                    @endforeach
                    
                    </select>
                </div>



                <div class="form-group">
                  <label for="exampleInputEmail1">tags</label>
                    <input class="form-control" id="tags" name="tags" value="{{old('tags','')}}"
                  placeholder ="Pisahkan dengan koma, contoh :postingan,beritaterkini,update">

                  </div>  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
            </div>
</div>


</section>


@endsection

@push('script-textEditor')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush()

resources/views/adminModul/artikel/edit.blade.php
@extends('adminpage.master')
@push('textEditor-tinyMCE')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Data Artikel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Artikel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
    <div class="col-md-12">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Artikel</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('artikel.update',['artikel' => $query -> id])}}" method="post" enctype="multipart/form-data">
              @csrf
              @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Judul</label>
                    <input class="form-control" name="judul" value="{{old('judul',$query ->judul)}}">
                  </div>
                  @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
                  <div class="form-group">
                  <label>Isi</label>
                  <textarea class="form-control my-editor" name="isi">{!! old('isi',$query ->isi) !!}
                  </textarea>
                      </div>
                      @error('isi')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
                  
                <div class="form-group">
                        <label for="exampleFormControlFile1">Tambah gambar</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1" name="gambar">
                        <a href="{{'../../../gambar_artikel/'.$query ->gambar}}" target="_blank">{{$query ->gambar}}</a>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">status Publikasi</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="status">
                    <option value="{{$query ->status}}">{{$query ->status}}</option>
                    <option value="YA">YA</option>
                    <option value="TIDAK">TIDAK</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="kategori">
                    <option value="{{$query -> id_kategori}}">{{$query ->kategori->nama_kategori}}</option>
                    @foreach($queryKategori as $key => $queryKategori )
                    <option value="{{$query -> id}}">{{$queryKategori -> nama_kategori}}</option>
                    @endforeach
                    
                    </select>
                </div>


                <div class="form-group">
                  <label for="exampleInputEmail1">tags</label>
                    <input class="form-control" id="tags" name="tags" value="{{old('tags')}}"
                  placeholder ="Pisahkan dengan koma, contoh :postingan,beritaterkini,update">
                 tags : @forelse ($query->tags as $tag)
                  #{{$tag->tag_name}}
                    @empty
                    No Tags
                  @endforelse
                  <br>*Jika tidak diubah lewatkan saja
                  </div>  
                </div>
            



                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
            </div>
</div>


</section>


@endsection

@push('script-textEditor')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush()

resources/views/adminModul/artikel/index.blade.php
@extends('adminpage.master')
@section('content')
<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Data Artikel</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Artikel</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
@if (session('berhasil'))
<div class="alert alert-success">
{{session('berhasil')}}
</div>
@endif
<!--<a class= "btn btn-primary mb-2" href="/artikel/create">Create</a>-->
<a class= "btn btn-primary mb-2" href="{{route('artikel.create')}}">Create</a>
<table class="table table-bordered">
  <thead>                  
    <tr>
      <th style="width: 10px">No</th>
      <th>Judul</th>
      <th>Isi</th>
      <th>Kategori</th>
      <th>Gambar</th>
      <th>Penulis</th>
      <th>Tanggal/Jam</th>
      <th style="width: 40px">Opsi</th>
    </tr>
  </thead>
  <tbody>
      @forelse($query as $key => $query )
     
    <tr>
      <td>{{$key + 1}}</td>
      <td>{{$query -> judul}}</td>
      <td>{!!Str::limit ($query -> isi,100, ' ....')!!}</td>
      <td>{{$query ->kategori->nama_kategori}}</td>
      <td><a href="{{'../gambar_artikel/'.$query -> gambar}}">{{$query -> gambar}}</a></td>
      <td>{{$query->author->name}}</td>
      <td>{{$query -> created_at}}</td>
      <td style="display: flex;">
      <a class= "btn btn-default btn-sm" href="{{route('artikel.edit',['artikel' => $query -> id],'edit')}}">edit</a>
      <form action="{{route('artikel.destroy',['artikel' => $query -> id])}}" method="post">
      @csrf
      @method('Delete')
      <input type="submit" class= "btn btn-danger btn-sm" value="Del">  </form>
      </td>
      
    </tr>
    @empty <p>No Data </p>
    @endforelse
    
  </tbody>
</table>
@endsection